name: usfs-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - numpy
  - requests
  - xarray
  - ipyleaflet
  - ipywidgets
  - shapely
  - matplotlib
  - ipympl
  